applied-exploration/modular-pipelines

- model/huggingface/infer.py
- run_pipeline.py
Infer output ```List[Tuple[Label, Probabilities]]```
> feat(Huggingface): Infer Pipeline aligned with Scikitlearn infer

- config.py
- model/huggingface/base.py
- model/huggingface/infer.py
- model/huggingface/train.py
- run_pipeline.py
- type.py
We don't need to fit if we already fitted.
> feat(Huggingface): Checking already trained model

- configs/config.py
- library/__init__.py
- library/examples/simple_decoder.py
- model/pytorch/base.py
- model/pytorch/decoder.py
- run_pipeline.py
- type.py
- Migrated from branch #pytorch to clean up the changes.
> feature(Model): Pytorch Lightning model integrated

- library/examples/simple_decoder.py
- model/augmenters/statistics.py
Changed it to give back only integers and floats.
> fix(Augmenter): Statistic Augmenter improved.

- blocks/adaptors/base.py
- blocks/augmenters/base.py
- blocks/base.py
- blocks/iomanager.py
- blocks/models/base.py
- blocks/transformations/base.py
- runner/run_pipeline.py
- runner/train.py
New class hierarchy:
```
Element
- DataSource
- Block
- Model
- Transformer
- Augmenters
- Adaptor
```
> feature(Classes): Transformers & Adaptors & Augmenters rely now on Blocks

- blocks/augmenters/spelling_autocorrect.py
- blocks/base.py
- blocks/models/base.py
- blocks/models/huggingface/base.py
- blocks/models/huggingface/infer.py
- blocks/models/pytorch/base.py
- blocks/models/sklearn/sklearn.py
- blocks/pipeline.py
- library/examples/hate_speech.py
- runner/evaluation.py
- runner/run_pipeline.py
- runner/store.py
- runner/train.py
- utils/json.py
> feature(Evaluation): evaluate per model if it has .evaluators

- blocks/pipeline.py
- plugins/__init__.py
- plugins/wandb_plugin.py
- run.py
Closes #65 
``Pipeline().get_configs()`` aggregates children and puts them according to their ``id`` in a dictionary. ``wandb`` processes this at launch.
> feature(Logging): Wandb now receives a full collection of the configs.

- blocks/augmenters/statistics.py
- blocks/base.py
- blocks/models/huggingface/base.py
- blocks/models/huggingface/train.py
- blocks/pipeline.py
- configs/constants.py
- environment.yml
- library/examples/hate_speech.py
- plugins/analyser_plugin.py
- plugins/base.py
- plugins/integrity_plugin.py
- plugins/wandb_plugin.py
- runner/runner.py
- runner/train.py
- type.py
- Our plugin now handles the logging of huggingface.
> feat(Wandb): Taking over huggingface process.

- blocks/transformations/no_lemmatizer.py
- blocks/transformations/tokenizer.py
- data/dataloader.py
- library/examples/hate_speech_sklearn.py
- plugins/analyser_plugin.py
- run.py
- type.py
> feature(Library): added sklearn ensemble pipeline in a separate file

- run.py
- run_multi.py
- runner/runner.py
- type.py
Closes #80 
We can add naming and arbitrary many runs in ``run_multi``
!!! Some run_config params are not hooked up yet to effectively do anything, I'm implementing it now.
> Feature(Runner): Runner configured through run config file.

- blocks/pipeline.py
> fix(Pipeline): deepcopy all blocks to avoid accidental parameter sharing

- blocks/models/random.py
- library/examples/hate_speech.py
- runner/evaluation.py
> feature(Models): added RandomModel, AllZerosModel, AllOnesModel

- data/merge.py
- data/transformation_hatespeech_detection.py
- data/transformation_hatespeech_offensive.py
- library/examples/hate_speech.py
> feature(Data): merge training data from 3 different sources

- environment.yml
- library/examples/hate_speech.py
- library/examples/hate_speech_multi_hf.py
- library/examples/hate_speech_sklearn.py
- run.py
- runner/runner.py
- type.py
> feature(Types): added Experiment type encompassing Pipelines, metrics, project_name, etc.

- blocks/base.py
- blocks/iomanager.py
- blocks/models/huggingface/base.py
- blocks/models/huggingface/train.py
- run.py
- runner/runner.py
- Naming of ``ids``
- Naming of ``parent_path`` was unified with naming of ``ids`` loop
- ``input_data`` source renaming was necessary.
> fix(Pipeline): Preparation of pipeline was fixed

- library/examples/hate_speech.py
I was mutating the same object, in an array comprehension before...
> fix(Experiments): deepcopy the experiment before setting the pipeline when we want to clone it

- blocks/adaptors/base.py
- blocks/augmenters/base.py
- blocks/base.py
- blocks/data.py
- blocks/ensemble.py
- blocks/models/base.py
- blocks/pipeline.py
- blocks/transformations/base.py
- runner/runner.py
- type.py
- utils/run_helpers.py
> feature(Hierarchy): We get ``hierarchy`` now as a class, typesafe.

- blocks/iomanager.py
- blocks/pipeline.py
- configs/constants.py
- plugins/__init__.py
- plugins/output_analyser_plugin.py
- run.py
- runner/runner.py
- runner/train.py
- utils/printing.py
- utils/run_helpers.py
This is a plugin that shows some insights into the input - prediction - labels to give a hunch how bad the system is.
This is different from ``evaluation`` and is intended for explainability rather than evaluating the performance.
> feature(Plugin): Output Analyser

- blocks/base.py
- blocks/iomanager.py
- blocks/models/huggingface/base.py
- blocks/pipeline.py
- run.py
- runner/runner.py
- type.py
- utils/run_helpers.py
> feature(Loading): If ``preferred_origin`` set, then no fallback. Naming starts with ``project_id``

- blocks/adaptors/base.py
- blocks/augmenters/base.py
- blocks/base.py
- blocks/io.py
- blocks/models/sklearn.py
- blocks/transformations/base.py
- blocks/transformations/sklearn.py
- data/merge.py
- library/examples/hate_speech.py
- library/examples/hate_speech_meta_sklearn.py
- library/examples/hate_speech_multi_hf.py
- library/examples/hate_speech_sklearn.py
- run.py
- runner/train.py
- type.py
> refactor(Types): flip `force_fit` to `frozen`

- blocks/models/random.py
- blocks/models/vader.py
> fix(Models): explicitly add empty save() & load() to random & vader models

- blocks/models/sklearn.py
- library/models/sklearn_simple.py
- library/models/sklearn_voting.py
- type.py
> feature(Models): added `calibrate` option to SKLearn

- library/experiments/hate_speech.py
- plugins/output_analyser_plugin.py
- run.py
- runner/runner.py
- runner/store.py
- utils/printing.py
> Feature(OutputAnalyser): Created a Correlation matrix metric

- blocks/models/perspective/__init__.py
- blocks/models/perspective/base.py
- environment.yml
- library/experiments/hate_speech_perspective.py
- run.py
> feature(Model): Perspective-API created and hooked up

- run.py
This way we execute the rest of the experiments.
> feature(Runner): ``try-except`` implemented on ``runner.run()``

- .gitignore
- blocks/models/huggingface/loading.py
- library/experiments/hate_speech_multi_type_hf.py
- output/failed_runs.txt
- run.py
- run_dev.py
- type.py
- utils/printing.py
> feature(Library): Multi-task pipeline for transformers.

- blocks/base.py
- library/evaluation/classification.py
- library/experiments/hate_speech.py
- library/experiments/hate_speech_baselines.py
- library/experiments/utils.py
- run_dev.py
`+`
- fix: Minor fixes that broke the main ``run.py`` 
- fix: ⚠️ Added ``average = 'micro'`` to ``f1_score``
- chore: Refractored experiment utils to a seperate file.
> feature(Library): Refractored and added baseline experiments.

- .github/workflows/test.yml
- blocks/base.py
- blocks/ensemble.py
- blocks/pipeline.py
- data/dataloader.py
- library/dataset/tweet_eval.py
- library/experiments/hate_speech.py
- run.py
- run_dev.py
- runner/runner.py
- tests/test_experiments.py
- utils/list.py
- We are checking if there are any failed experiment
- We are checking if the stats of the successful runs are in the correct range.
> feature(Testing): Integration test added.

- blocks/pipeline.py
- tests/test_experiments.py
- tests/test_unittests.py
- utils/dict.py
- feature(Utils): Dictionary to list
- feature(Test): Testing obj_to_dict
> chore(Pipeline): Refractoring functions

- blocks/base.py
- blocks/transformations/tokenizer.py
- data/dataloader.py
- utils/spacy.py
Instead of waiting 8-10 seconds for all datasets to load, now they only load when they're needed. speeds up debugging a lot!
> fix(Blocks): speed up spacy tokenizer, only load Dataset when necessary (speed up initial phase)

- blocks/pipeline.py
- library/experiments/hate_speech_baselines.py
- plugins/wandb_plugin.py
- run.py
- run_dev.py
- runner/utils.py
- tests/test_experiments.py
- tests/test_unittests.py
- type.py
- utils/dict.py
> feature(Plugin): Wandb now correctly logs the config of mutated pipeline.

- src/mopi/blocks/augmenters/spelling_autocorrect.py
- src/mopi/blocks/augmenters/spelling_spello.py
- src/mopi/blocks/io.py
- src/mopi/blocks/models/perspective/base.py
- src/mopi/blocks/models/pytorch/base.py
- src/mopi/blocks/transformations/lemmatizer.py
- src/mopi/blocks/transformations/no_lemmatizer.py
- src/mopi/blocks/transformations/tokenizer.py
- src/mopi/library/experiments/hate_speech_baselines.py
- src/mopi/run_inference.py
- src/mopi/run_training.py
- src/mopi/run_training_dev.py
- src/mopi/runner/runner.py
- tests/test_experiments.py
> Feature(IO): Pickling shouldn't pickle models or loaded data.
